import 'bootstrap/dist/css/bootstrap.css'
import './style/globals.css'
import Navigation from '@/components/Navigation/Navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" />
      </head>
      <body suppressHydrationWarning={true}>

        <Navigation />

        {children}
      </body>
    </html>
  )
}
