import 'bootstrap/dist/css/bootstrap.css'
import './style/globals.css'
import Link from "next/link"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" />
      </head>
      <body suppressHydrationWarning={true}>

        <nav className="navbar navbar-expand-lg bg-body-tertiary px-3">
          <div className="container-fluid">
            <Link href={'/'} className="navbar-brand">MOVIES APP</Link>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse justify-content-end" id="navbarNav">
              <ul className="navbar-nav gap-2">

                <li className="nav-item">
                  <Link href={'/'}>HOME</Link>
                </li>
                <li className="nav-item">
                  <Link href={'/movies'}>MOVIES</Link>
                </li>
                <li className="nav-item">
                  <Link href={'/about'}>ABOUT</Link>
                </li>

              </ul>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  )
}
