import Link from "next/link"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href={'/'}>GO HOME | </Link>
        <Link href={'/movies'}>GO MOVIES | </Link>
        <Link href={'/about'}>GO ABOUT | </Link>
        {children}
      </body>
    </html>
  )
}
